In [1]:
import pandas as pd

In [2]:
url="https://drive.google.com/file/d/1y0vJeEgyLo6QUXU1oqSoop_zMkzX0XDo/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
data = pd.read_csv(path)

In [5]:
url="https://drive.google.com/file/d/1Cd2IceiX4yTHLZCwB9Vse0JCjIRPX9lU/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
gdp_data= pd.read_csv(path)

In [6]:
pd.set_option("display.max_rows",500)

In [7]:
df=data.copy()
gdp_df =gdp_data.copy()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 454 entries, 0 to 453
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country Name                  454 non-null    object
 1   City                          188 non-null    object
 2   Country Code                  453 non-null    object
 3   Region                        404 non-null    object
 4   IncomeGroup                   404 non-null    object
 5   PPP Ratio
(2024)              452 non-null    float64
 6   Std Family
Urban
(Annual)     454 non-null    object
 7   Std Family
Rural
(Annual)     454 non-null    object
 8   Typical Fam
Urban
(Annual)    454 non-null    object
 9   Typical Fam
Rural
(Annual)    454 non-null    object
 10  Single Indiv
Urban
(Annual)   454 non-null    object
 11  Single Indiv
Rural
(Annual)   454 non-null    object
 12  Single Parent
Urban
(Annual)  454 non-null    object
 13  Single Parent
Rural
(Annual)  454 non-null    object
 14  Source                        454 non-null    object
dtypes: float64(1), object(14)
memory usage: 53.3+ KB

In [9]:
df.shape

(454, 15)

In [10]:
df.head()

,Country Name,City,Country Code,Region,IncomeGroup,PPP Ratio\n(2024),Std Family\nUrban\n(Annual),Std Family\nRural\n(Annual),Typical Fam\nUrban\n(Annual),Typical Fam\nRural\n(Annual),Single Indiv\nUrban\n(Annual),Single Indiv\nRural\n(Annual),Single Parent\nUrban\n(Annual),Single Parent\nRural\n(Annual),Source
0,Aruba,NaN,ABW,Latin America & Caribbean,High income,0.780,"USD 23,689","USD 13,445","USD 21,126","USD 11,687","USD 18,851","USD 9,702","USD 37,398","USD 19,955",PPP Model
1,Africa Eastern and Southern,NaN,AFE,NaN,NaN,0.000,"USD 10,608","USD 5,906","USD 10,346","USD 5,778","USD 7,471","USD 3,821","USD 16,510","USD 8,522",Aggregate
2,Afghanistan,NaN,AFG,Middle East & North Africa,Low income,0.000,"USD 9,977","USD 5,581","USD 9,573","USD 5,349","USD 7,047","USD 3,595","USD 15,499","USD 8,037",Income Avg
3,Africa Western and Central,NaN,AFW,NaN,NaN,0.000,"USD 10,608","USD 5,906","USD 10,346","USD 5,778","USD 7,471","USD 3,821","USD 16,510","USD 8,522",Aggregate
4,Angola,NaN,AGO,Sub-Saharan Africa,Lower middle income,0.263,"USD 7,854","USD 4,373","USD 7,709","USD 4,321","USD 5,341","USD 2,717","USD 12,139","USD 6,238",PPP Model

In [11]:
# clean the column names
df.columns = df.columns.str.replace('\n', ' ').str.strip()

In [12]:
# create the list of columns that contain currency/money values

currency_cols = [
    'Std Family Urban (Annual)', 'Std Family Rural (Annual)',
    'Typical Fam Urban (Annual)', 'Typical Fam Rural (Annual)',
    'Single Indiv Urban (Annual)', 'Single Indiv Rural (Annual)',
    'Single Parent Urban (Annual)', 'Single Parent Rural (Annual)'
]

# Clean and convert to numeric
# Convert to string to handle 'USD' or ',' if they exist
for col in currency_cols:
    df[col] = df[col].astype(str).str.replace('USD', '', regex=False)
    df[col] = df[col].str.replace(',', '', regex=False)

# Convert to numeric
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [13]:
#  Adding a representative column
df['Median(LW)'] = (df[currency_cols].median(axis=1)).round(0)

In [14]:
df.head()

,Country Name,City,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),Single Indiv Urban (Annual),Single Indiv Rural (Annual),Single Parent Urban (Annual),Single Parent Rural (Annual),Source,Median(LW)
0,Aruba,NaN,ABW,Latin America & Caribbean,High income,0.780,23689,13445,21126,11687,18851,9702,37398,19955,PPP Model,19403.0
1,Africa Eastern and Southern,NaN,AFE,NaN,NaN,0.000,10608,5906,10346,5778,7471,3821,16510,8522,Aggregate,7996.0
2,Afghanistan,NaN,AFG,Middle East & North Africa,Low income,0.000,9977,5581,9573,5349,7047,3595,15499,8037,Income Avg,7542.0
3,Africa Western and Central,NaN,AFW,NaN,NaN,0.000,10608,5906,10346,5778,7471,3821,16510,8522,Aggregate,7996.0
4,Angola,NaN,AGO,Sub-Saharan Africa,Lower middle income,0.263,7854,4373,7709,4321,5341,2717,12139,6238,PPP Model,5790.0

**URBAN RURAL COST GAP ANALYSIS**

In [15]:
# Calculate the percentage difference for a standard family urban vs rural
df['U/R Gap%(std fam)'] = (((df['Std Family Urban (Annual)'] - df['Std Family Rural (Annual)']) /
                            df['Std Family Rural (Annual)']) * 100).round(2)

In [16]:
# Calculate the percentage difference for a single parent urban vs rural
df['U/R Gap%(single parent)'] = (((df['Single Parent Urban (Annual)'] - df['Single Parent Rural (Annual)']) /
                            df['Single Parent Rural (Annual)']) * 100).round(2)

In [17]:
# Calculate the percentage difference for a single individual urban vs rural
df['U/R Gap%(single individual)'] = (((df['Single Indiv Urban (Annual)'] - df['Single Indiv Rural (Annual)']) /
                            df['Single Indiv Rural (Annual)']) * 100).round(2)

In [18]:
# Calculate the percentage difference for a Typical Fam urban vs rural
df['U/R Gap%(Typical Fam)'] = (((df['Typical Fam Urban (Annual)'] - df['Typical Fam Rural (Annual)']) /
                            df['Typical Fam Rural (Annual)']) * 100).round(2)

**SINGLE PARENT FINANCIAL BURDEN**

In [19]:
# finanacial burden of a single parent in urban area by comparing standard family
df['(Sing parent burden% vs std fam(U))']=((df['Single Parent Urban (Annual)']-df['Std Family Urban (Annual)'])/df['Std Family Urban (Annual)']*100).round(2)

In [20]:
df.head()

,Country Name,City,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),...,Single Indiv Rural (Annual),Single Parent Urban (Annual),Single Parent Rural (Annual),Source,Median(LW),U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U))
0,Aruba,NaN,ABW,Latin America & Caribbean,High income,0.780,23689,13445,21126,11687,...,9702,37398,19955,PPP Model,19403.0,76.19,87.41,94.30,80.76,57.87
1,Africa Eastern and Southern,NaN,AFE,NaN,NaN,0.000,10608,5906,10346,5778,...,3821,16510,8522,Aggregate,7996.0,79.61,93.73,95.52,79.06,55.64
2,Afghanistan,NaN,AFG,Middle East & North Africa,Low income,0.000,9977,5581,9573,5349,...,3595,15499,8037,Income Avg,7542.0,78.77,92.85,96.02,78.97,55.35
3,Africa Western and Central,NaN,AFW,NaN,NaN,0.000,10608,5906,10346,5778,...,3821,16510,8522,Aggregate,7996.0,79.61,93.73,95.52,79.06,55.64
4,Angola,NaN,AGO,Sub-Saharan Africa,Lower middle income,0.263,7854,4373,7709,4321,...,2717,12139,6238,PPP Model,5790.0,79.60,94.60,96.58,78.41,54.56

In [19]:
#finanacial burden of a single parent in rural area by comparing standard family
df['(Sing parent burden% vs std fam(R))']=((df['Single Parent Rural (Annual)']-df['Std Family Rural (Annual)'])/df['Std Family Rural (Annual)']*100).round(2)

In [22]:
# Calculate the absolute parenting penalty factor for a single earner/
#df['financial burden(Sing parent vs indiv(U))'] = (df['Single Parent Urban (Annual)'] / df['Single Indiv Urban (Annual)']).round(2)

If the result is $1.0$: Children cost nothing extra.If the result is $2.2$: It means a single parent must earn 2.2 times (or 120% more than) what a solo adult needs just to cover basic survival and childcare in that city.

In [23]:
# # Rural parenting penalty
# df['Rural_Parent_penality'] = df['Single Parent Rural (Annual)'] / df['Single Indiv Rural (Annual)']

# # # Compare the Urban Penalty vs Rural Penalty
# df['Childcare'] = df['Sing_parent_penalty(vs indiv)'] - df['Rural_Parent_penality']

In [24]:
# # 1. Raw cash cost of children in the city
# Urban_Child_Cost = df['Single Parent Urban (Annual)'] - df['Single Indiv Urban (Annual)']

# # 2. Raw cash cost of children in the countryside
# Rural_Child_Cost= df['Single Parent Rural (Annual)'] - df['Single Indiv Rural (Annual)']

# # 3. The True Cash Urban Childcare Premium
# df['Childcare Premium(Urban)'] = Urban_Child_Cost - Rural_Child_Cost

In [26]:
# split the dataframe into 3 parts-city,aggregate,country

In [21]:
# create a separate dataframe for city
# Cities: Rows where 'City' is NOT null
df_cities = df[df['City'].notnull()].copy()  #country code,region,income group 1 null value  --taiwan
df_cities.shape

(188, 21)

In [22]:
  # create aggregate dataframe
 # Aggregates: Rows where Region is NaN (These are usually regional or global summaries)
df_aggregates = df[df['Region'].isnull()& df['City'].isnull()].copy()
df_aggregates.shape

(49, 21)

In [23]:
# create country dataframe
# Countries: Rows where 'City' is null AND 'Region' is NOT null
df_countries = df[df['City'].isnull() & df['Region'].notnull()].copy()
df_countries=df_countries.drop('City',axis=1)
df_countries.shape

(217, 20)

In [24]:
#  Verification-always good to check that the counts add up
print(f"Total Rows: {len(df)}")
print(f"Aggregates (NaN Region): {len(df_aggregates)}")
print(f"Cities: {len(df_cities)}")
print(f"Countries: {len(df_countries)}")

Total Rows: 454
Aggregates (NaN Region): 49
Cities: 188
Countries: 217

In [25]:
# Sort the dataframe by 'Country Name' in ascending order
df_cities = df_cities.sort_values(by='Country Name', ascending=True)
df_countries = df_countries.sort_values(by='Country Name', ascending=True)

In [26]:
df_cities.head()

,Country Name,City,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),...,Single Indiv Rural (Annual),Single Parent Urban (Annual),Single Parent Rural (Annual),Source,Median(LW),U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U))
321,Argentina,Buenos Aires,ARG,Latin America & Caribbean,Upper middle income,0.459,18194,9786,16774,8824,...,6369,28871,14405,Numbeo City,13766.0,85.92,100.42,106.11,90.10,58.68
401,Armenia,Yerevan,ARM,Europe & Central Asia,Upper middle income,0.375,15519,7830,15802,7936,...,5724,24888,11585,Numbeo City,12176.0,98.20,114.83,123.03,99.12,60.37
341,Australia,Melbourne,AUS,East Asia & Pacific,High income,0.896,28422,14835,25587,13113,...,10861,45652,22282,Numbeo City,22296.0,91.59,104.88,105.41,95.13,60.62
340,Australia,Canberra,AUS,East Asia & Pacific,High income,0.896,25938,12925,23283,11343,...,11111,41791,19290,Numbeo City,20596.0,100.68,116.65,97.11,105.26,61.12
339,Australia,Brisbane,AUS,East Asia & Pacific,High income,0.896,25337,12845,22736,11282,...,9723,41536,19738,Numbeo City,20580.0,97.25,110.44,120.32,101.52,63.93

In [27]:
#  Reset the index for all three to start from 0
df_aggregates = df_aggregates.reset_index(drop=True)
df_cities = df_cities.reset_index(drop=True)
df_countries = df_countries.reset_index(drop=True)

In [28]:
# remove NaN columns
df_aggregates=df_aggregates.drop(columns=['City','Region','IncomeGroup','PPP Ratio (2024)'])

In [29]:
df_cities.info() #missing values in 1 column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Country Name                         188 non-null    object
 1   City                                 188 non-null    object
 2   Country Code                         187 non-null    object
 3   Region                               187 non-null    object
 4   IncomeGroup                          187 non-null    object
 5   PPP Ratio (2024)                     187 non-null    float64
 6   Std Family Urban (Annual)            188 non-null    int64
 7   Std Family Rural (Annual)            188 non-null    int64
 8   Typical Fam Urban (Annual)           188 non-null    int64
 9   Typical Fam Rural (Annual)           188 non-null    int64
 10  Single Indiv Urban (Annual)          188 non-null    int64
 11  Single Indiv Rural (Annual)          188 non-null    int64
 12  Single Parent Urban (Annual)         188 non-null    int64
 13  Single Parent Rural (Annual)         188 non-null    int64
 14  Source                               188 non-null    object
 15  Median(LW)                           188 non-null    float64
 16  U/R Gap%(std fam)                    188 non-null    float64
 17  U/R Gap%(single parent)              188 non-null    float64
 18  U/R Gap%(single individual)          188 non-null    float64
 19  U/R Gap%(Typical Fam)                188 non-null    float64
 20  (Sing parent burden% vs std fam(U))  188 non-null    float64
dtypes: float64(7), int64(8), object(6)
memory usage: 31.0+ KB

In [42]:
#Ethiopia’s,venezuela  income group is missing in the dataset& unclassified since 2021 by world bank

In [31]:
# # Filter the aggregate data to only show the main Income Groups
income_labels = ['Low income', 'Lower middle income', 'Upper middle income', 'High income']
df_income_comparison = df_aggregates[df_aggregates['Country Name'].isin(income_labels)].copy()
df_income_comparison

,Country Name,Country Code,Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),Single Indiv Urban (Annual),Single Indiv Rural (Annual),Single Parent Urban (Annual),Single Parent Rural (Annual),Source,Median(LW),U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U))
13,High income,HIC,22128,12429,19753,10854,17500,8975,35020,18450,Aggregate,17975.0,78.04,89.81,94.99,81.99,58.26
24,Low income,LIC,9977,5581,9573,5349,7047,3595,15499,8037,Aggregate,7542.0,78.77,92.85,96.02,78.97,55.35
25,Lower middle income,LMC,11134,6194,10662,5934,8026,4092,17376,8973,Aggregate,8500.0,79.75,93.65,96.14,79.68,56.06
47,Upper middle income,UMC,12352,6933,11622,6453,9088,4637,19272,10053,Aggregate,9570.0,78.16,91.70,95.99,80.10,56.02

In [33]:
# change the median column to city_median
df_cities = df_cities.rename(columns={'Median(LW)': 'city_median'}).copy()

In [34]:
#  Basic Dimensions Check  ## there is a 'London' in the United Kingdom, and a 'London' in Ontario, Canada(so city name unique=187)
print(f"Total Unique Cities: {df_cities['City'].nunique()}")
print(f"Total Unique Countries Represented: {df_cities['Country Name'].nunique()}")

Total Unique Cities: 187
Total Unique Countries Represented: 75

In [36]:
expensive_cities = df_cities.sort_values(by='city_median', ascending=False)
expensive_cities.head()

,Country Name,City,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),...,Single Indiv Rural (Annual),Single Parent Urban (Annual),Single Parent Rural (Annual),Source,city_median,U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U))
151,United States,"New York, NY",USA,North America,High income,1.000,77078,30483,71013,27616,...,23638,130141,47886,Numbeo City,53248.0,152.86,171.77,147.95,157.14,68.84
144,United Kingdom,London,GBR,Europe & Central Asia,High income,0.849,54751,26922,50391,24494,...,23680,89905,41762,Numbeo City,46076.0,103.37,115.28,120.13,105.73,64.21
149,United States,"San Francisco, CA",USA,North America,High income,1.000,53603,28431,48929,25632,...,23151,87881,44110,Numbeo City,46072.0,88.54,99.23,107.48,90.89,63.95
170,United States,"Brooklyn, NY",USA,North America,High income,1.000,60679,26798,55629,24155,...,21355,100583,41218,Numbeo City,44316.0,126.43,144.03,122.03,130.30,65.76
183,United States,"Boston, MA",USA,North America,High income,1.000,53510,24657,48963,22194,...,21047,88635,38095,Numbeo City,42494.0,117.02,132.67,122.81,120.61,65.64

In [38]:
expensive_cities.tail(5)

,Country Name,City,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),...,Single Indiv Rural (Annual),Single Parent Urban (Annual),Single Parent Rural (Annual),Source,city_median,U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U))
59,India,Chennai,IND,South Asia,Lower middle income,0.241,5623,3299,5264,3085,...,1854,8649,4722,Numbeo City,4134.0,70.45,83.16,91.26,70.63,53.81
64,India,Ahmedabad,IND,South Asia,Lower middle income,0.241,5397,3158,5051,2953,...,1872,8289,4504,Numbeo City,3874.0,70.90,84.04,73.24,71.05,53.59
45,Egypt,Cairo,EGY,Middle East & North Africa,Lower middle income,0.175,5436,2883,5673,3110,...,1913,8538,4156,Numbeo City,3846.0,88.55,105.44,84.89,82.41,57.06
61,India,Kolkata,IND,South Asia,Lower middle income,0.241,5201,2698,4869,2523,...,1461,8175,3867,Numbeo City,3418.0,92.77,111.40,103.29,92.98,57.18
89,Nepal,Kathmandu,NPL,South Asia,Lower middle income,0.252,5048,2639,5065,2646,...,1509,7787,3676,Numbeo City,3357.0,91.28,111.83,101.33,91.42,54.26

In [53]:
## df_cities ---all city data --188 rows
## df_countries ---all country_data(including ppp=0),217 rows
## df_aggregates ---grouped data --49 rows

## countries_new ---new table to compare city median with country median
# country_gdp ---country table including gdp percapita(ppp)

In [39]:
# df to compare city and country median
countries_new = df_countries[['Country Name', 'Country Code', 'Median(LW)']]
countries_new .head()

     Country Name Country Code  Median(LW)
0     Afghanistan          AFG      7542.0
1         Albania          ALB      9690.0
2         Algeria          DZA      4778.0
3  American Samoa          ASM     17975.0
4         Andorra          AND     16051.0

In [40]:
# Rename 'Median(LW)' to 'country_median' in the new table
countries_new  = countries_new .rename(columns={'Median(LW)': 'country_median'})
countries_new .head()

     Country Name Country Code  country_median
0     Afghanistan          AFG          7542.0
1         Albania          ALB          9690.0
2         Algeria          DZA          4778.0
3  American Samoa          ASM         17975.0
4         Andorra          AND         16051.0

In [41]:
countries_new .shape

(217, 3)

In [42]:
# merge city cities_df with country_new ,after merging 172 rows present in the table (based on the country name)
countries_new = df_cities[['Country Name','City','Region','IncomeGroup','city_median']].merge(
  countries_new [['Country Name','country_median']],
    on='Country Name')

In [43]:
countries_new.head()

,Country Name,City,Region,IncomeGroup,city_median,country_median
0,Argentina,Buenos Aires,Latin America & Caribbean,Upper middle income,13766.0,10699.0
1,Armenia,Yerevan,Europe & Central Asia,Upper middle income,12176.0,11277.0
2,Australia,Melbourne,East Asia & Pacific,High income,22296.0,19107.0
3,Australia,Canberra,East Asia & Pacific,High income,20596.0,19107.0
4,Australia,Brisbane,East Asia & Pacific,High income,20580.0,19107.0

In [44]:
countries_new.shape

(172, 6)

In [45]:
median_diff=countries_new.loc[
    countries_new['city_median'] > countries_new['country_median']]
median_diff.head()

,Country Name,City,Region,IncomeGroup,city_median,country_median
0,Argentina,Buenos Aires,Latin America & Caribbean,Upper middle income,13766.0,10699.0
1,Armenia,Yerevan,Europe & Central Asia,Upper middle income,12176.0,11277.0
2,Australia,Melbourne,East Asia & Pacific,High income,22296.0,19107.0
3,Australia,Canberra,East Asia & Pacific,High income,20596.0,19107.0
4,Australia,Brisbane,East Asia & Pacific,High income,20580.0,19107.0

In [47]:
# Calculate exactly by how much the city exceeds the nation (as a percentage)
countries_new['% comparison National&city median'] = (
    (countries_new['city_median'] - countries_new['country_median'])
    / countries_new['country_median'] * 100
).round(2)

In [48]:
countries_new.loc[countries_new['% comparison National&city median']<0].shape

(24, 7)

In [49]:
# GDP per capita dataset
gdp_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,37524.914920,39287.059713,38543.907294,28854.597300,35104.786804,41758.895757,46574.357420,50649.301523,NaN,NaN
1,Africa Eastern and Southern,AFE,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3837.726375,3723.216423,3801.413183,3708.094649,4028.376504,4369.191056,4501.601101,4635.788224,NaN,NaN
2,Afghanistan,AFG,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2335.795862,2432.276701,2583.485332,2561.981761,2144.166570,2122.995815,2201.722907,NaN,NaN,NaN
3,Africa Western and Central,AFW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5026.648499,5179.359990,5484.249418,5414.042540,5690.967743,6220.122875,6520.280313,6815.990961,NaN,NaN
4,Angola,AGO,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8006.836615,8278.368862,8572.878956,7827.428043,8862.281333,9588.241295,9753.600468,10118.608995,NaN,NaN

In [53]:
# Extract and fill missing values using the exact year column names
# This matches the string columns '2024', '2023', and '2022'
gdp_df['GDP per capita(ppp)'] = gdp_df['2024'].fillna(gdp_df['2023']).fillna(gdp_df['2022']).round()
gdp_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70,GDP per capita(ppp)
0,Aruba,ABW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,39287.059713,38543.907294,28854.597300,35104.786804,41758.895757,46574.357420,50649.301523,NaN,NaN,50649.0
1,Africa Eastern and Southern,AFE,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3723.216423,3801.413183,3708.094649,4028.376504,4369.191056,4501.601101,4635.788224,NaN,NaN,4636.0
2,Afghanistan,AFG,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2432.276701,2583.485332,2561.981761,2144.166570,2122.995815,2201.722907,NaN,NaN,NaN,2202.0
3,Africa Western and Central,AFW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5179.359990,5484.249418,5414.042540,5690.967743,6220.122875,6520.280313,6815.990961,NaN,NaN,6816.0
4,Angola,AGO,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8278.368862,8572.878956,7827.428043,8862.281333,9588.241295,9753.600468,10118.608995,NaN,NaN,10119.0

In [56]:
# Keep only the columns need for merge
# select 'Country Code' because it is a reliable 3-letter key
gdp_df_clean = gdp_df[['Country Code', 'GDP per capita(ppp)']].copy()
gdp_df_clean.shape

(266, 2)

In [57]:
gdp_df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country Code         266 non-null    object
 1   GDP per capita(ppp)  247 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.3+ KB

In [58]:
# filter the rows where the GDP is missing
gdp_df_clean.loc[gdp_df_clean['GDP per capita(ppp)'].isnull()].shape

(19, 2)

In [60]:
gdp_df_clean.loc[gdp_df_clean['GDP per capita(ppp)'].isnull()].shape

(19, 2)

In [61]:
# to calculate the affordability index every gdp per capita (ppp) should be >0 ,so filtering those list ith Nan values
gdp_df_new= gdp_df_clean[gdp_df_clean['GDP per capita(ppp)'] > 0]
gdp_df_new.shape    # 19 rows removed and go with 247 rows for this analysis

(247, 2)

In [63]:
gdp_df_new.head()

  Country Code  GDP per capita(ppp)
0          ABW              50649.0
1          AFE               4636.0
2          AFG               2202.0
3          AFW               6816.0
4          AGO              10119.0

In [64]:
# merge gdp df with df_countries
# This connects the datasets using the 'Country Code' column present in both
country_gdp = df_countries.merge(gdp_df_new, on='Country Code', how='inner')

In [65]:
country_gdp.shape

(199, 21)

The Affordability Index

    Q. Which countries have the highest and lowest cost of survival relative to their economic status?

In [68]:
#  Calculate the PPP Affordability Index using the Living Wage column of std family -urban
country_gdp['Aff_Index(std_fam_urban)']= (country_gdp['Std Family Urban (Annual)'] / country_gdp['GDP per capita(ppp)']).round(1)

In [72]:
# check how many countries that has affordability index greater than 0.40
country_gdp.loc[country_gdp['Aff_Index(std_fam_urban)']>0.40].head()

,Country Name,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),Single Indiv Urban (Annual),...,Single Parent Rural (Annual),Source,Median(LW),U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U)),GDP per capita(ppp),Aff_Index(std_fam_urban)
0,Afghanistan,AFG,Middle East & North Africa,Low income,0.000,9977,5581,9573,5349,7047,...,8037,Income Avg,7542.0,78.77,92.85,96.02,78.97,55.35,2202.0,4.5
1,Albania,ALB,Europe & Central Asia,Upper middle income,0.426,12342,7011,11505,6350,9294,...,10087,Numbeo,9690.0,76.04,89.92,95.99,81.18,55.22,26702.0,0.5
4,Angola,AGO,Sub-Saharan Africa,Lower middle income,0.263,7854,4373,7709,4321,5341,...,6238,PPP Model,5790.0,79.60,94.60,96.58,78.41,54.56,10119.0,0.8
5,Antigua and Barbuda,ATG,Latin America & Caribbean,High income,0.705,21383,12115,19239,10656,16769,...,17914,PPP Model,17342.0,76.50,88.07,94.51,80.55,57.56,33386.0,0.6
7,Armenia,ARM,Europe & Central Asia,Upper middle income,0.375,14546,7484,14805,7583,11511,...,11043,Numbeo,11277.0,94.36,110.38,120.39,95.24,59.71,22823.0,0.6

In [69]:
# sort by affordability index value
country_gdp.sort_values(by='Aff_Index(std_fam_urban)', ascending=False).head()

,Country Name,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),Single Indiv Urban (Annual),...,Single Parent Rural (Annual),Source,Median(LW),U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U)),GDP per capita(ppp),Aff_Index(std_fam_urban)
35,Central African Republic,CAF,Sub-Saharan Africa,Low income,0.409,12275,6888,11590,6462,8895,...,9984,PPP Model,9440.0,78.21,91.66,95.67,79.36,55.89,1263.0,9.7
161,Solomon Islands,SLB,East Asia & Pacific,Lower middle income,0.723,21929,12429,19687,10901,17260,...,18396,PPP Model,17828.0,76.43,87.91,94.46,80.60,57.64,2675.0,8.2
193,Vanuatu,VUT,East Asia & Pacific,Lower middle income,0.946,28832,16420,25277,13951,23594,...,24542,PPP Model,24068.0,75.59,86.16,93.90,81.18,58.46,3606.0,8.0
162,"Somalia, Fed. Rep.",SOM,Sub-Saharan Africa,Low income,0.393,11797,6615,11177,6234,8500,...,9575,PPP Model,9038.0,78.34,91.91,95.72,79.29,55.76,1602.0,7.4
102,Liberia,LBR,Sub-Saharan Africa,Low income,0.455,13696,7700,12809,7132,10081,...,11205,PPP Model,10643.0,77.87,90.94,95.44,79.60,56.21,1871.0,7.3

In [73]:
country_gdp.sort_values(by='Aff_Index(std_fam_urban)', ascending=False).tail(5)

,Country Name,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),Single Indiv Urban (Annual),...,Single Parent Rural (Annual),Source,Median(LW),U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U)),GDP per capita(ppp),Aff_Index(std_fam_urban)
133,Norway,NOR,Europe & Central Asia,High income,0.851,23809,14229,20869,12231,19976,...,20754,Numbeo,20365.0,67.33,77.85,91.03,70.62,55.03,102038.0,0.2
147,Russian Federation,RUS,Europe & Central Asia,High income,0.314,10618,5963,9197,5042,8159,...,8650,Numbeo,8404.0,78.06,91.57,100.76,82.41,56.07,47405.0,0.2
26,Brunei Darussalam,BRN,East Asia & Pacific,High income,0.369,11061,6195,10538,5882,7897,...,8946,PPP Model,8422.0,78.55,92.34,95.86,79.16,55.56,89879.0,0.1
106,"Macao SAR, China",MAC,East Asia & Pacific,High income,0.567,17133,9670,15715,8727,13019,...,14185,PPP Model,13602.0,77.18,89.50,94.95,80.07,56.89,126960.0,0.1
75,Guyana,GUY,Latin America & Caribbean,High income,0.370,11102,6219,10574,5902,7931,...,8982,PPP Model,8456.0,78.52,92.31,95.88,79.16,55.58,80155.0,0.1

In [75]:
#  Calculate the PPP Affordability(single individual urban) Index using the Living Wage column
country_gdp['Aff_Index(Sin_Indv_Urban)']= (country_gdp['Single Indiv Urban (Annual)'] / country_gdp['GDP per capita(ppp)']).round(1)

In [77]:
country_gdp.loc[country_gdp['Aff_Index(Sin_Indv_Urban)']>0.40]
country_gdp.sort_values(by='Aff_Index(Sin_Indv_Urban)', ascending=False).head()

,Country Name,Country Code,Region,IncomeGroup,PPP Ratio (2024),Std Family Urban (Annual),Std Family Rural (Annual),Typical Fam Urban (Annual),Typical Fam Rural (Annual),Single Indiv Urban (Annual),...,Source,Median(LW),U/R Gap%(std fam),U/R Gap%(single parent),U/R Gap%(single individual),U/R Gap%(Typical Fam),(Sing parent burden% vs std fam(U)),GDP per capita(ppp),Aff_Index(std_fam_urban),Aff_Index(Sin_Indv_Urban)
35,Central African Republic,CAF,Sub-Saharan Africa,Low income,0.409,12275,6888,11590,6462,8895,...,PPP Model,9440.0,78.21,91.66,95.67,79.36,55.89,1263.0,9.7,7.0
161,Solomon Islands,SLB,East Asia & Pacific,Lower middle income,0.723,21929,12429,19687,10901,17260,...,PPP Model,17828.0,76.43,87.91,94.46,80.60,57.64,2675.0,8.2,6.5
193,Vanuatu,VUT,East Asia & Pacific,Lower middle income,0.946,28832,16420,25277,13951,23594,...,PPP Model,24068.0,75.59,86.16,93.90,81.18,58.46,3606.0,8.0,6.5
117,"Micronesia, Fed. Sts.",FSM,East Asia & Pacific,Lower middle income,0.958,29217,16643,25585,14119,23955,...,PPP Model,24422.0,75.55,86.08,93.87,81.21,58.51,4347.0,6.7,5.5
102,Liberia,LBR,Sub-Saharan Africa,Low income,0.455,13696,7700,12809,7132,10081,...,PPP Model,10643.0,77.87,90.94,95.44,79.60,56.21,1871.0,7.3,5.4

In [81]:
#  Calculate the PPP Affordability(single parent urban) Index using the Living Wage column
country_gdp['Aff_Index(sin_parent_Urban)']= (country_gdp['Single Parent Urban (Annual)'] / country_gdp['GDP per capita(ppp)']).round(1)

In [82]:
#  Calculate the PPP Affordability(country median) Index using  median(LW)
country_gdp['Aff_Index(country_med)']= (country_gdp['Median(LW)'] / country_gdp['GDP per capita(ppp)']).round(1)

In [83]:
#  Calculate the PPP Affordability(typical family urban) Index using the living wage column
country_gdp['Aff_Index(Typ fam urban)']= (country_gdp['Typical Fam Urban (Annual)'] / country_gdp['GDP per capita(ppp)']).round(1)

In [84]:
#  Filter, select columns, and sort in ascending order
affordable_countries = country_gdp.loc[
    country_gdp['Aff_Index(country_med)'] < 0.40,
    ['Country Name', 'Aff_Index(country_med)']
].sort_values(by='Aff_Index(country_med)', ascending=True)

# Display the result
print(affordable_countries)

             Country Name  Aff_Index(country_med)
26      Brunei Darussalam                     0.1
75                 Guyana                     0.1
152          Saudi Arabia                     0.1
106      Macao SAR, China                     0.1
27               Bulgaria                     0.2
34         Cayman Islands                     0.2
16                Belarus                     0.2
3                 Andorra                     0.2
49                Denmark                     0.2
54       Egypt, Arab Rep.                     0.2
47                 Cyprus                     0.2
70              Greenland                     0.2
37                  Chile                     0.2
145                 Qatar                     0.2
20                Bermuda                     0.2
13                Bahrain                     0.2
91             Kazakhstan                     0.2
133                Norway                     0.2
134                  Oman                     0.2
132       North Macedonia                     0.2
146               Romania                     0.2
147    Russian Federation                     0.2
115             Mauritius                     0.2
112                 Malta                     0.2
85                Ireland                     0.2
96                 Kuwait                     0.2
109              Malaysia                     0.2
105            Luxembourg                     0.2
83     Iran, Islamic Rep.                     0.2
94            Korea, Rep.                     0.2
150            San Marino                     0.2
157             Singapore                     0.2
182               Turkiye                     0.2
188  United Arab Emirates                     0.2
171                Sweden                     0.2
80                Iceland                     0.3
66                Georgia                     0.3
79                Hungary                     0.3
67                Germany                     0.3
69                 Greece                     0.3
39               Colombia                     0.3
48                Czechia                     0.3
57                Estonia                     0.3
10                Austria                     0.3
2                 Algeria                     0.3
63                 France                     0.3
60          Faroe Islands                     0.3
62                Finland                     0.3
11             Azerbaijan                     0.3
9               Australia                     0.3
14             Bangladesh                     0.3
104             Lithuania                     0.3
87                  Italy                     0.3
81                  India                     0.3
89                  Japan                     0.3
95                 Kosovo                     0.3
99                 Latvia                     0.3
144      Puerto Rico (US)                     0.3
142                Poland                     0.3
120            Montenegro                     0.3
128           New Zealand                     0.3
17                Belgium                     0.3
25                 Brazil                     0.3
38                  China                     0.3
159       Slovak Republic                     0.3
154                Serbia                     0.3
143              Portugal                     0.3
160              Slovenia                     0.3
172           Switzerland                     0.3
176              Thailand                     0.3
164                 Spain                     0.3
170              Suriname                     0.3
181               Tunisia                     0.3
180   Trinidad and Tobago                     0.3
183          Turkmenistan                     0.3
190         United States                     0.3
191               Uruguay                     0.3

In [91]:
##  convert cleaned data to csv file for creating dashboard

In [85]:
# COUNTRY DATA

#  Make a copy
country_cl = df_countries.copy()
#  Export to a clean CSV file
country_cl.to_csv('country_cl.csv', index=False)

In [86]:
# AGGREGATES TABLE

#  Make a copy
aggregates_cl = df_aggregates.copy()
#  Export to a clean CSV file
aggregates_cl.to_csv('aggregates_cl.csv', index=False)

In [87]:
# CITY DATA

#  Make a dedicated copy
cities_cl = df_cities.copy()
#  Export to a clean CSV file
cities_cl.to_csv('cities_cl.csv',index=False)

In [90]:
# CITY -COUNTRY MEDIAN COMPARISON
#  Make a dedicated copy
city_country_median=countries_new.copy()
#  Export to a clean CSV file
city_country_median.to_csv('city_country_median_cl.csv',index=False)

In [91]:
# COUNTRY GDP Data

#  Make a dedicated
Country_gdppc=country_gdp.copy()
#  Export to a clean CSV file
Country_gdppc.to_csv('Country_gdppc_cl.csv',index=False)